import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import "../globals.css";
import "@/app/globals.css";
import Link from "next/link";
import Header from "@/components/header";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log('hero子路由组的layout渲染了');
  return (
    <>
      <Header />
      {children}
    </>
  );
}